FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch-20190612
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN apt-get update && \
  apt-get install -yq \
    python3 \
    python3-dev \
    python3-pip \
    python3-setuptools \
  && apt-get clean && rm -rf /var/lib/apt/lists/*
COPY ./requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt
ENV UDEV=1
CMD ["python3", "app.py"]
